language: php

php:
  - 7.2
  - 7.1
  - 7.0
  - hhvm
  - nightly

dist: trusty

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  allow_failures:
    - php: nightly

install:
  - travis_retry composer install --prefer-dist --no-interaction --no-suggest

script: vendor/bin/phpunit
